### ISSUE TITLE
"Could not add AmaryllisGrid/GospelWorld to the grid list. ..." (Even though AmG/GW are already in the Grid list)

### ISSUE THREAD

**Issue by life777eternal** [HalcyonGrid/halcyon#114]
Is there any way that this: https://jira.firestormviewer.org/browse/FIRE-30593 could be an issue on the Halcyon grid itself?  Because it never appeared on the older versions of FirestormOS. I've seen it on both AmG and GW now.  Than ye.

Have any of you tried the new **MAJOR Firestorm Viewer Release** yet? **Firestorm 6.4.12 (62831)** See the details on it here: https://firestormviewer.org/firestorm-6-4-12-62831/ 
Since installing both new versions, I have noticed a few issues that affects the new version in Amaryllis Grid (AmG) & Gospel World (GW), and one of which also affects the older versions. I have posted a couple new issues recently on the Firestorm Jira. If you've had any similar experience with the new Firestorm Version please do comment on these. Although in order to do so, you'd have to create an account on the FS Jira, and/or login there. Thank ye.
https://jira.firestormviewer.org/browse/FIRE-30604 https://jira.firestormviewer.org/browse/FIRE-30605

**Comment by emperorstarfinder** [comment]
So it looks like this is relating to being able to add the grid to your grids list.

Whenever you get this message: 

`Could not add AmaryllisGrid to the grid list.
Server didn't provide grid info: 0
Please check if the loginuri is correct and contact support of
AmaryllisGrid`

it usually means either you have entered the URL of the grid incorrectly or the grid service is down i.e. grid server.  This usually will not be an issue that the viewer devs will consider a viewer bug but rather will do as Ansariel has told you to do which is contact the grid owner.    Therefore I think it is probably safe to say this is not an issue with the project but rather the grid itself.  I recommend contacting the grid owner for assistance as per the message the viewer has told you.  If it's Gospel World or Amarylis grid then I am quite sure Vinhold can help you there.

Otherwise, I have noticed no issues adding grids to the latest Firestorm.

Best Regards.

**Comment by life777eternal** [comment]
Well maybe aye and maybe naw @emperorstarfinder It could be something related to the Halcyon Grid, or it could be something related to the changes made in the new version of FirestormOS Firestorm 6.4.12 (62831) on Amaryllis Grid (AmG) & Gospel World (GW). Also I wasn't trying to add any grid to the grid list, that just has been mysteriously popping up, twice after teleporting/loggin in, and several times after that.  Those two grids have been added to the grid list for several months already.

Thank you, Shalom.

**Comment by emperorstarfinder** [comment]
We have had EEP on our grid for more than a month along with the protocol in our viewer.  EEP itself will not affect teleporting, however, we have had people tell us they couldn't successfully teleport.  Sometimes a failed teleport causes people to be offline when in fact they are online.  Usually, a simple relog has corrected this along with us restarting the affected regions.  This usually is not a viewer issue, it just means the region has become desynced with the grid services.  Theoretically, this shouldn't happen with Halcyon because of its persistence mechanisms which are better than OpenSimulator's but it is possible that the regions have become desynced.  In which case restarting grid and region services should correct that.  Because Halcyon regions only are able to run on Windows due to the physics engine the windows VMs or servers may need a restart as well.  We usually do a rolling restart of our grid, region, web, and server hardware on a weekly basis to help prevent this from happening.  

Halcyon also does not support EEP and some of the newer features rolled out in the latest Firestorm and if I am being honest, I don't foresee the support arriving in the immediate short term so you may run into issues due to there not being support in Halcyon's codebase for newer things in the new viewer release and future releases.  So it is worth keeping that in mind.

Best regards

**Comment by life777eternal** [comment]
No the the new EEP UI doesn't affect the teleporting. It might just not be completely compatible with all the Halycon and Opensim grids though(as you did mention), and the the FS devs didn't make it abundantly clear that it's the '**X**' next to "**Personal Lighting...**" that is needed to click on to restore the default region Windlight. Because apparently the devs said that selecting "**Shared Environment**" beside "**Sky**," "**Water**," & "**Day Cycle**" in the **Phototools** is not meant to do anything, but I've found that it does do something on Halcyon and Opensim(Amaryllis Grid, Gospel World, Osgrid, & Great Canadian Grid), changes it to the first Windlight in the list, just not the desired affect being the default region Windlight. **Though that popup message I've been seeing isn't related to the new EEP UI.** Also I haven't had any "failed teleports" at least not that I realized, although I did notice once that a short IM on AmG was sent to my email while I was apparently online, and then received it in-world after a relog. (How would a person recognize a "failed teleport" ?)

Thank you @emperorstarfinder  Shalom

**Comment by emperorstarfinder** [comment]
The viewer will tell you if the teleport fails.  There will, however, be times that a teleport will succeed but you will be seen as offline though you are in fact online.  The easiest way to know that is if someone is in front of you in the same region but they cannot see your ID in their friends' list as online.  This usually means your seen as offline.  This happened to us a few months back in which case it is just a matter of a bug that was introduced early on that caused the slurls to be incorrect.  However, while that was a bug on our grid, it is unlikely that the bug is in the halcyon codebase as our internal halcyon testbed grid works just fine.  Usually, when an email is sent with an instant message you didn't receive in-world that means you actually are seen as offline by the grid service even though you are online.  In most cases, this is caused by the region your in becoming desynced.  Usually, a relog will fix that and then teleporting after a relog in addition to the grid owner doing a rolling restart of grid and region services to ensure all grid and region services are communicating properly.  The best remedy for halcyon users would be to use the latest Firestorm that is Pre-EEP to avoid any potential issues relating to EEP that could be caused, though I suspect your problem is more an issue with a region becoming desynced with the grid services.

The Sky, Water, and Day Cycle in phototools does pretty much what the old windlight does.  EEP is essentially just a modern approach to the old out of date legacy windlight.  The real noticeable difference with EEP is that you can change the texture of the sun and moon and things like that.  Otherwise, the rest is pretty similar to the old Windlight.

Best regards

**Comment by Streexfoxtrot** [comment]
From what we saw when this popped up ..it was the viewer itself. Not the grid that is causing this. (and yes mine had the grid in the directory just fine, but it kept popping up) so it's the version of the viewer you're using.

**Comment by life777eternal** [comment]
Aye @Streexfoxtrot it's a problem on the viewer, not the grid.

**Comment by mdickson** [comment]
This is both a viewer and a grid problem.  There is a Gridinfo field that's not being correctly returned to the viewer from the Grid Service.  Based on conversation with UBit he indicated it should be mandatory so Beq made it that way in the viewer.  Older versions of both OpenSim and current Halcyon return the error you're seeing because they dont supply this "mandatory" field.  I believe Beq is changing things for the next release to not require it which will fix the problem but the region code could also supply it and then it would work as expected with any FS including the current released one.

**Comment by life777eternal** [comment]
Hi @mdickson it seemed like the viewer has been pulling the "`gridnick`" from the `Halcyon.ini` file, and I think that's why the message has been slightly different on different Halcyon Grids. Aye, it looks like [Beq Janus](https://jira.firestormviewer.org/secure/ViewProfile.jspa?name=beqphoenixjira) has applied a fix for this scenario for the next beta version of FS. Also now that you mention it, I see that "`[GridInfo]`" entry under the "`[Economy]`" tag, in the `Halcyon.ini` file, it's commented out by default (have not setup the Economy on my Halcyon grid, so not sure if it get's automatically un-commented out if/when the Economy is setup). 

Beq said:
> ... however with respect to incomplete config. the viewer was updated on the advice of OpenSim core to expect gatekeepURI as this is (supposedly) mandatory. It does not appear to be the case for a number of grids though and it falls back to the last ditch method, which then fails (see below). ...

You probably saw his comment on the issue I posted on the Firestorm Jira, if not it's [here](https://jira.firestormviewer.org/browse/FIRE-30593?focusedCommentId=214630&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-214630). Beq did explain it there.

**Comment by mdickson** [comment]
There was a firestorm update yesterday that may fix this issue (at least on the viewer a workaround for it).   It's still worth looking at adding a gatekeeperURI entry as Beq detailed IMO to the server but this firestorm workaround makes the issue less problematic.

**Comment by life777eternal** [comment]
Oh thanks @mdickson ... aye this should be fixed in 6.4.13 release. 

"**AN UPDATE? ALREADY?**" https://firestormviewer.org/firestorm-6-4-1363251-release/
