### ISSUE TITLE
WALT

### ISSUE THREAD

**Issue by Yichard** [HalcyonGrid/halcyon#118]
Undisclosed, as it is a safety issue. 

The result of this is the nearby complete disappearance of the whole content of the sim, save a random selection of scripted items gathered around 0 0 0. So it is a severe issue.

**Comment by Yichard** [comment]
commenting out the faulty old code should be enough. although in discussions some found that this code is interesting and deserves a closer examination.

**Comment by kf6kjg** [comment]
Please DM me the details in Discord.

**Comment by Yichard** [comment]
The result of this is the nearby complete disappearance of the whole content of the sim, save a random selection of scripted items gathered around 0 0 0. So it is a severe issue.

**Comment by kf6kjg** [comment]
Thank you for the DM. This should be a priority.

**Comment by mdickson** [comment]
Is there some place information on this is being placed?  If its an exploit I understand keeping it private assuming anyone can do it but IDK how it gets triaged and fixed without it being accessible somewhere

**Comment by kf6kjg** [comment]
Mike, while I’ve no fixed plan or central place for how to handle security issues like this in the general case - mainly due to this being the first one in the class - know that it is being handled. If things grow enough I’ll have to solve the general case and probably create a private issue the tracker or something. For now just reporting the consequences here and DMing me the triggers is enough.

**Comment by kf6kjg** [comment]
Fixed in release 0.9.42.
