### ISSUE TITLE
Fire/T-Pose Script characteristics remaining after script has been deleted

### ISSUE THREAD

**Issue by life777eternal** [HalcyonGrid/halcyon#149]
Greetings, I have a house in Sovaria Estates that I imported with Singularity from an XML file. Recently I tried to add a fire script to one of the fireplace, though the first firelog I added the script to is still acting like a fire, even though I have already deleted the script.

Would there be any reason for this? Thank you

![Fireplace_007](https://user-images.githubusercontent.com/25623649/211696786-69332cb3-e247-4ae5-9228-d4bf69694886.png)

**Comment by Yichard** [comment]
This is the intended  behavior in SL, Halcyon and Open Sims, and unlikely to be changed.
The reason is that these are prim properties, which are set by the script. The script just runs once when it starts (the "state_entry()" event), and it remains inactive afterward.
To stop the behavior, you need to drop a scrubber script in the prim (all freebies script shop have one)
Another solution is to run the same script with a zero value.  For instance for the hover text:
 llSetText( "", vector color, float alpha );    This one contains a null text.
 Resettin the script will just replay the "state_entry()" event, restarting the behavior we want to stop.
 There are other animation properties which remain : hover text, all particles, texture anim, omega rotation, physics, etc.
 There also are multiple script methods to change prim properties when you need to, for instance having a variable fire.
 
 While everybody is free to report suspected bugs or to demand improvement, you understand that this one is likely to be closed.

**Comment by sonjamichelle** [comment]
So? Issue solved?

If so, please close this issue to keep the git issues list clean.

Glad it worked out.
