### ISSUE TITLE
Offline message

### ISSUE THREAD

**Issue by Ana-Green** [HalcyonGrid/halcyon#87]
Offline message  do  fail, not able  to send an offline  message  this  did  occur after  the upgrade  

[00:29:55] Melanie Bell: (Saved Wed May 22 16:24:54 2019)hi Frank are u there?
[00:29:55] Melanie Bell: (Saved Wed May 22 16:25:16 2019) I finished avatars and I sended u
[00:29:55] Melanie Bell: (Saved Thu May 23 07:23:36 2019)where is here one sandbox
[00:29:55] Melanie Bell: (Saved Thu May 23 07:24:31 2019)cant rezz nothing
[01:09:27] Grid Owner: Here is the LM to the SandBox Melanie - Hugs  :)  ♥♥
[01:09:28] Melanie Bell: User is not logged in. Message not saved
[01:09:53] Grid Owner: Here is the LM to the SandBox Melanie - Hugs  :)  ♥♥
[01:09:54] Melanie Bell: User is not logged in. Message not saved

Regards,
Ana Green

**Comment by kf6kjg** [comment]
Does your INI file have OfflineMessageModule equal to OfflineMessageModule
and OfflineMessageURL set to the page that handles offline messages? If so, then verify that that page is functional. Please post the results.

**Comment by Ana-Green** [comment]
My dad will look soon, Vinhold has set up this part will post the result ASAP

Regards,
Ana Green

**Comment by Ana-Green** [comment]
[Messaging]
    ; Control which region module is used for instant messaging.
    ; Default is InstantMessageModule (this is the name of the core IM module as well as the setting)
    InstantMessageModule = InstantMessageModule
    MessageTransferModule = MessageTransferModule
    OfflineMessageModule = OfflineMessageModule
    OfflineMessageURL = http://dreamcastle-entertainment.eu/offline.aspx
    MuteListModule = MuteListModule
    MuteListURL = https://dreamcastle-entertainment.eu/mute.aspx

Regards,
Ana Green

**Comment by kf6kjg** [comment]
Then I'd recommend testing to see if the `http://dreamcastle-entertainment.eu/offline.aspx` page is working correctly.

**Comment by Ana-Green** [comment]
its working, Bob did this:: extended the offline table binary bucket field from varchar(45) to varchar(80) to resolve DB write error for now. now it's working again 

Regards,
Ana Green

**Comment by Ana-Green** [comment]
Viewer  =  Firestorm 5.0.11 (53634) Jan  9 2018 20:02:54 (Firestorm-Releasex64) with OpenSimulator support

Regards,
Ana Green

**Comment by Vinhold** [comment]
The offlines.aspx page detected and reported in is log file a DB error for invalid content being posted to the offline table binarybucket field. Due to similar error in ran into with AmarylissGrid installation, I extended the field size to varchar(80) and now the DB error is not a problem. I have been informed that Group Messages attachments are the real source of the issue, and they do not work, attachments may be set, but recipients cannot access or open them. The offlines DB error was a clue to possible reason why the error has not been found yet. Now that the field is taking the full data sent to it, perhaps it can be traced as to what part is at fault: the saving of the attachment or the reading of the attachment.

**Comment by Vinhold** [comment]
NOTE: This is a duplicate issue for issue #77 I posted earlier.

**Comment by kf6kjg** [comment]
Closing in favor of #77, thank you.
